### PR TITLE
[release-2.5] Upgrade vulnerable dependencies

### PR DESCRIPTION
**Pull request by jlpadilla**
Signed-off-by: Jorge Padilla <jpadilla@redhat.com>

**Related Issue:**  stolostron/backlog#22734

### Description of changes
- PR for main #181
- PR for release-2.6 #182

### CODE REVIEW

**Comment by jlpadilla** [comment]
/hold 
release-2.5 is currently on code freeze.

**Review by SherinV — APPROVED** [review]

**Review by SherinV — APPROVED** [review]

**Comment by jlpadilla** [comment]
Waiting for release-2.5 to reopen.

**Review by Anxhela21 — APPROVED** [review]
/lgtm

**Pull request merged**
